### ISSUE TITLE
deprecation warnings by sequelize

### ISSUE THREAD

**Issue by machinshin** [ozum/sequelize-pg-generator#1]
emits: 
"Utils deprecated Non-object references property found. Support for that will be removed in version 4. Expected { references: { model: "value", key: "key" } } instead of { references: "value", referencesKey: "key" }. node_modules/sequelize/lib/model.js:85:25

**Comment by ozum** [comment]
Hi,

Please use [pg-generator](http://www.pg-generator.com) module and it's [sequelize template](http://www.pg-generator.com/builtin-templates/sequelize/). [pg-generator](http://www.pg-generator.com) is successor of this module and it generates much more better sequelize code. Also it can be modified according to your needs easily.

About your question for this module. You can use sequelize 4 template to avoid this warning.

```
spgen ........ -t sequelize4
```

**Comment by machinshin** [comment]
ah, thanks on both counts!
