### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by wuher** [ozum/sequelize-pg-generator#10]
I'm unable to run the tests. I tried with `npm test` and `make test` but both fail. Here's the output:

```bash

echo Starting test *********************************************************
Starting test History.md LICENSE Makefile README-JSDOC-TR.md README-JSDOC.md README-TR.md README.md config doc jsdoc-conf.json lib model node_modules package.json template test
./node_modules/mocha/bin/mocha


  1) "before all" hook
  2) "after all" hook

  0 passing (4s)
  2 failing

  1)  "before all" hook:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/Users/jedi/projects/sequelize-pg-generator/node_modules/mocha/lib/runnable.js:159:19)
      at Timer.listOnTimeout (timers.js:89:15)

  2)  "after all" hook:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/Users/jedi/projects/sequelize-pg-generator/node_modules/mocha/lib/runnable.js:159:19)
      at Timer.listOnTimeout (timers.js:89:15)



make: *** [test] Error 2
npm ERR! Test failed.  See above for more details.
```

**Comment by ozum** [comment]
Hi,

    make test

or

    mocha test

commands run tests.

Although individual tests in this library are fine, preparing part of the tests are not so well written (test/util directory). Preparing part create temporary database to run tests against. In some systems this may result timeout. In those cases running tests second time or running individually may or may not solve problem.

    mocha test/generate.js

I wrote another library to handle tests better, but not had time to implement in sequelize-pg-generator.
