### ISSUE TITLE
Support for PascalCase in model names

### ISSUE THREAD

**Issue by wuher** [ozum/sequelize-pg-generator#13]
In our projects we've had a convention to use _PascalName_ casing in model names. Currently `spgen` only supports _camelCase_. I looked at the code and I think it would be very simple change but the question comes down to how to configure it.

1. change `generate.modelCamelCase` = true/false to `generate.modelCasing` = "camel" | "pascal" | "snake" | null
2. simply add `generate.modelPascalCase` which defaults to `false`

Problem with 1. is that it's backward incompatible unless we support both for some time and add deprecation warnings.

Problem with 2. is that it's not very intuitive to have both options (`modelCamelCase` and `modelPascalCase`).

Also, should we also support _PascalCase_ for `relationAccessor` and `columnAccessor` ? To me, those don't seem that important.

What do you think?

**Comment by ozum** [comment]
For consistency if PascalCase is added it should be added for all naming tyes including model names, column accessors etc.

First alternative is more future proof. It would be backward compatible to have both `generate.modelCamelCase` and `generate.modelCase` at the same time for a while and producing depreciation warning for true values of generate.modelCamelCase.

**Comment by wuher** [comment]
Thank you for the feedback. Right now, I'm not doing anything about this. Maybe later. I think we can close it for now and I'll come back to it if becomes an issue.

**Comment by ozum** [comment]
@wuher pg-sequelize-generator is renamed pg-generator. New version is more flexible. You can now generate with pascal case.

    $ pgen template sequelize -t sequelize-template

    --> Search generated template files for 'camelCase' and replace them with pascalCase. <--

    $ pgen exec sequelize-template -d our_crm -u user -p tOpSeCrEt -t model
