### ISSUE TITLE
Missing utils.js file when use sequelize4 template

### ISSUE THREAD

**Issue by zxqfox** [ozum/sequelize-pg-generator#15]
To rename file according to docs I should use utils.js file. But I don't have this file when using sequelize4 template to generate models.

Is there any workaround for it (to rename an attribute)?

**Comment by ozum** [comment]
I checked the source code and found mistakes false instructions in created files listed below:

1. utils.js file is created for every template, but its location is written false. It should be ../../utils.js
2. custom model files naming and location i written false.

I corrected them and updated in github and npm.

Could you please check if it works as expected now?

**Comment by zxqfox** [comment]
Oh, right. Not sure why you expose utils out of model but yes, now it's consistent. Thanks

**Comment by ozum** [comment]
@zxqfox FYI: Location of utils.js is changed. It is located inside of model directory as of v0.7.0, where it should be in the first place.
