### ISSUE TITLE
get error when I run spgen

### ISSUE THREAD

**Issue by machinshin** [ozum/sequelize-pg-generator#2]
--- spgen.config.json 
```javascript
{
    "sequelize-pg-generator":  {
        "database": {
            "host": "localhost",
            "port": 5432,
            "database": "mydb",
            "user": "root",
            "schema": ["public"]
        },
        "output": {
            "log": true,
            "folder": "./src/models",
            "beautify": true,
            "indent": 4,
            "preserveNewLine": true,
            "warning": true
        },
        "generate": {
            "useSchemaName": false,
            "stripFirstTableFromHasMany": true,
            "stripFirstTableFromManyToMany": true,
            "belongsToMany": true,
            "columnDescription": true,
            "tableDescription": true
        },
        "tableOptions": {
            "timestamps": true,
            "updatedAt": "modified_at"
        }
    }
}
```
when i run: 
```bash
$ spgen -p mypassword --config spgen.config.json
info: (Created) Index file:[project-directory]/src/models/index.js
[Error: Schema's Child Object "mydb.public.atable" cannot be found in tables.]
```
(names changed to protect the innocent ;) )
not sure what is going on here, what am i missing?

**Comment by ozum** [comment]
I need a schema dump SQL to check this. If it is not possible to share your schema, create a similar basic database which produces same error. I guess a few tables will be enough. Since your problem is not related to fields, tables may contain only id, name and FK fields.

**Comment by machinshin** [comment]
ok. i'll work on making up some test tables & such today, thanks!

is there anyway to get spgen to give more debug info, maybe i can track it a bit myself?

**Comment by ozum** [comment]
Unfortunately spgen only provides debug info as you see it. I can't promise but consider add more debug info for future versions.

**Comment by machinshin** [comment]
well this is odd. it must have something to do with the user i created. 
```sql
mydb-# \du
                             List of roles
 Role name |                   Attributes                   | Member of
-----------+------------------------------------------------+-----------
 root      |                                                | {}
 vat       | Superuser, Create role, Create DB, Replication | {}
```
if i try to use the 'user root' it fails w/ the error above. 
if use user 'vat', code gets generated fine.

**Comment by ozum** [comment]
Check if user has read privilege to "mydb.public.atable".

**Comment by ozum** [comment]
Assuming it is a privilege problem which is not related to spgen, I close this issue.
