### ISSUE TITLE
[New Features] Support JSONB type

### ISSUE THREAD

**Issue by kimthangatm** [ozum/sequelize-pg-generator#4]
`This version cannot support JSON type`

**Comment by ozum** [comment]
Please describe the problem more detailed and with a sample code.

**Comment by viniciuspinto** [comment]
This is actually an issue with [pg-structure](https://github.com/ozum/pg-structure), I submitted a pull request to add support for JSONB.

**Comment by ozum** [comment]
Thanks @viniciuspinto. I was on holiday, looking now.

**Comment by ozum** [comment]
pg-structure is updated to latest version.
