### ISSUE TITLE
Tables with same name in different schemas. 

### ISSUE THREAD

**Issue by ramraas** [ozum/sequelize-pg-generator#5]
Tables with same name in different schemas. While generating the models spgen by passing array of schemas, it is confusing in relations and generating relations pointing to the table in another schema.

**Comment by ozum** [comment]
@ramraas. To overcome those and similar problems, use [pg-generator](https://github.com/ozum/pg-generator) which is successor of this project.

[pg-generator](https://github.com/ozum/pg-generator) uses nunjucks based templates to generate code. So you can customize it easily as you wish.

You can also access documentation on http://www.pg-generator.com
