### ISSUE TITLE
adding global options to all models after generation

### ISSUE THREAD

**Issue by machinshin** [ozum/sequelize-pg-generator#6]
so i'd like to add hooks & classMethods to every generated table (in my case, i added some code to custom code to the generated models/index.js

```
var globalOptions = {
    classMethods : {
        findByGUID: function(guid, attributes, includes) {
            return this.find(_.extend({
                where: { guid: guid },
            }, [{ attributes: attributes }, { includes: includes }]));
        }
    },
    hooks: {
        afterFind: function(instance) {
            if(!instance) { throw new Error("No instance with specificied guid!");}
            return instance;
        }
    }
};

```
then changed, defineModel() to => 
```
function defineModel(file) {
    var object      = require(file),
        options     = _.(object.options || {}, globalOptions),
        modelName   = object.modelName;

    fs.writeSync(debugFD, 'var ' + modelName + ' = Sequelize.define("' + modelName + '",\n' + util.inspect(object.attributes) + ',\n' + util.inspect(options, {depth: null}) + ');\n\n\n');

    models[modelName] = sequelize.define(modelName, object.attributes, options);
    if (object.relations !== undefined) {
        relationships[modelName] = object.relations;
    }
}
```

Obviously i'd rather not modify generated code, and since this code is intended to the same for every model, i wont' want to duplicate it in every /definition-files-custom/[table.js] file. 

is there a better way, or hopefully you could add one?

**Comment by ozum** [comment]
sequelize-pg-generator does not have this feature. However all code is generated via templates, so you can try to write custom templates. Have a look in template folder.

If it solves your problem, please post a message how you solved it for others.
