### ISSUE TITLE
Upgrade to handle breaking change comming with sequelize 4.0 about the references property of model attributes

### ISSUE THREAD

**Issue by rbecheras** [ozum/sequelize-pg-generator#8]
Using  `sequelize-pg-generator` with  ` 3.0.1 <= sequelize < 4.0` throw this warning:

> Utils deprecated Non-object references property found. Support for that will be removed in version 4. Expected { references: { model: "value", key: "key" } } instead of { references: "value", referencesKey: "key" }. at node_modules/sequelize/lib/model.js:80:25

Its related to this breaking change comming with 4.0.1, deprecated in 3.0.1:

> [CHANGED] The references property of model attributes has been transformed to an object: {type: Sequelize.INTEGER, references: { model: SomeModel, key: 'some_key' }}. The former format (references and referecesKey) still exists but is deprecated and will be removed in 4.0.

See http://docs.sequelizejs.com/en/latest/changelog/ > 3.0.1

**Comment by ozum** [comment]
Hi,

Thank you for reporting problem. To protect backward compatibility and support this new feature, I added new template called "sequelize4". Default template works as before. Also I added a test for this.

I created a Git branch: sequelize4-template. This should solve the problem you mentioned. Please download and report your mileage. If everything is as expected, I will merge it into master branch.

Hope this helps,

Best Regards,

**Comment by rbecheras** [comment]
Thank you for your reactivity. 

I will test it as soon as possible and come back

**Comment by wuher** [comment]
At least it got rid of the deprecation warning and everything seems to work. Thanks

**Comment by zxqfox** [comment]
Thanks guys!
